name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalação do PHP e extensões
        run: sudo apt-get install -y php php-xml php-mbstring
      - name: Instalação do composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
      - name: Instalação das dependências
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Lint PHP
        run: ./vendor/bin/phpcs --standard=PSR12 src/

  build:
    runs-on: ubuntu-latest
    needs: preflight
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: echo "A etapa de build não é necessária para este projeto PHP."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Instalação do PHP e extensões
        run: sudo apt-get install -y php php-xml php-mbstring
      - name: Instalação do composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
      - name: Instalação das dependências
        run: composer install
      - name: Rodar testes unitários
        run: echo "Aqui será a etapa para rodar os testes unitários."

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Configuração do Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
      - name: Tag release
        run: |
          git tag -a "v$(date +'%Y.%m.%d.%H%M%S')" -m "Generated tag from GitHub Actions"
          git push --tags
